/**
 * Mock data for the backoffice while the C# backend is not ready.
 * Remove this file once real endpoints are connected.
 */

import type {
  Film,
  User,
  Review,
  FilmList,
  Thread,
  DashboardStats,
  ActivityItem,
} from './api';

export const mockFilms: Film[] = [
  {
    id: '1',
    title: 'Dune: Part Two',
    year: 2024,
    director: 'Denis Villeneuve',
    genre: 'Sci-Fi',
    posterUrl: '',
    synopsis: 'Paul Atreides unites with the Fremen while on a warpath of revenge against the conspirators who destroyed his family.',
    runtime: 166,
    rating: 4.5,
    reviewCount: 2341,
    status: 'published',
    createdAt: '2024-03-01T00:00:00Z',
    updatedAt: '2024-03-15T00:00:00Z',
  },
  {
    id: '2',
    title: 'Interstellar',
    year: 2014,
    director: 'Christopher Nolan',
    genre: 'Sci-Fi',
    posterUrl: '',
    synopsis: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
    runtime: 169,
    rating: 4.7,
    reviewCount: 5120,
    status: 'published',
    createdAt: '2014-11-07T00:00:00Z',
    updatedAt: '2024-01-10T00:00:00Z',
  },
  {
    id: '3',
    title: 'The Grand Budapest Hotel',
    year: 2014,
    director: 'Wes Anderson',
    genre: 'Comedy',
    posterUrl: '',
    synopsis: 'A writer encounters the owner of an aging high-class hotel, who tells him of his early years serving as a lobby boy.',
    runtime: 99,
    rating: 4.3,
    reviewCount: 3210,
    status: 'published',
    createdAt: '2014-03-28T00:00:00Z',
    updatedAt: '2024-02-14T00:00:00Z',
  },
  {
    id: '4',
    title: 'Parasite',
    year: 2019,
    director: 'Bong Joon-ho',
    genre: 'Thriller',
    posterUrl: '',
    synopsis: 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
    runtime: 132,
    rating: 4.6,
    reviewCount: 4500,
    status: 'published',
    createdAt: '2019-05-30T00:00:00Z',
    updatedAt: '2024-03-01T00:00:00Z',
  },
  {
    id: '5',
    title: 'Untitled Project',
    year: 2025,
    director: 'TBD',
    genre: 'Drama',
    posterUrl: '',
    synopsis: 'A film currently in pre-production.',
    runtime: 0,
    rating: 0,
    reviewCount: 0,
    status: 'draft',
    createdAt: '2024-03-20T00:00:00Z',
    updatedAt: '2024-03-20T00:00:00Z',
  },
];

export const mockUsers: User[] = [
  {
    id: '1',
    username: 'alex_morgan',
    email: 'alex@example.com',
    role: 'admin',
    status: 'active',
    filmCount: 342,
    reviewCount: 128,
    listCount: 15,
    joinedAt: '2023-01-15T00:00:00Z',
    lastActiveAt: '2024-03-20T14:30:00Z',
  },
  {
    id: '2',
    username: 'cinema_lover',
    email: 'cinema@example.com',
    role: 'user',
    status: 'active',
    filmCount: 567,
    reviewCount: 89,
    listCount: 23,
    joinedAt: '2023-06-20T00:00:00Z',
    lastActiveAt: '2024-03-19T10:00:00Z',
  },
  {
    id: '3',
    username: 'film_critic_42',
    email: 'critic@example.com',
    role: 'moderator',
    status: 'active',
    filmCount: 1200,
    reviewCount: 456,
    listCount: 45,
    joinedAt: '2022-11-01T00:00:00Z',
    lastActiveAt: '2024-03-20T16:45:00Z',
  },
  {
    id: '4',
    username: 'spammer123',
    email: 'spam@example.com',
    role: 'user',
    status: 'banned',
    filmCount: 0,
    reviewCount: 12,
    listCount: 0,
    joinedAt: '2024-03-01T00:00:00Z',
    lastActiveAt: '2024-03-05T08:00:00Z',
  },
];

export const mockReviews: Review[] = [
  {
    id: '1',
    filmId: '1',
    filmTitle: 'Dune: Part Two',
    userId: '2',
    username: 'cinema_lover',
    rating: 5,
    content: 'Villeneuve turns silence into tension. A masterpiece of sci-fi cinema that stands alongside the greatest.',
    likesCount: 234,
    commentsCount: 18,
    status: 'published',
    createdAt: '2024-03-05T12:00:00Z',
  },
  {
    id: '2',
    filmId: '2',
    filmTitle: 'Interstellar',
    userId: '3',
    username: 'film_critic_42',
    rating: 4.5,
    content: 'A film that makes you feel both the vastness of space and the intimacy of human love.',
    likesCount: 189,
    commentsCount: 12,
    status: 'published',
    createdAt: '2024-02-20T09:30:00Z',
  },
  {
    id: '3',
    filmId: '3',
    filmTitle: 'The Grand Budapest Hotel',
    userId: '2',
    username: 'cinema_lover',
    rating: 4,
    content: 'Wes Anderson at his most whimsical and precise. Every frame is a delight.',
    likesCount: 145,
    commentsCount: 8,
    status: 'published',
    createdAt: '2024-02-14T16:00:00Z',
  },
  {
    id: '4',
    filmId: '1',
    filmTitle: 'Dune: Part Two',
    userId: '4',
    username: 'spammer123',
    rating: 1,
    content: 'BUY CHEAP WATCHES AT...',
    likesCount: 0,
    commentsCount: 0,
    status: 'flagged',
    createdAt: '2024-03-10T03:00:00Z',
  },
];

export const mockLists: FilmList[] = [
  {
    id: '1',
    title: 'Best Sci-Fi of the 21st Century',
    description: 'A curated collection of the finest science fiction films from 2000 onwards.',
    userId: '3',
    username: 'film_critic_42',
    filmCount: 25,
    likesCount: 567,
    visibility: 'public',
    createdAt: '2024-01-10T00:00:00Z',
    updatedAt: '2024-03-15T00:00:00Z',
  },
  {
    id: '2',
    title: 'Oscar Winners Collection',
    description: 'Every Best Picture winner compiled in one list.',
    userId: '1',
    username: 'alex_morgan',
    filmCount: 96,
    likesCount: 1230,
    visibility: 'public',
    createdAt: '2023-06-15T00:00:00Z',
    updatedAt: '2024-03-10T00:00:00Z',
  },
  {
    id: '3',
    title: 'My Watchlist',
    description: 'Films I need to watch.',
    userId: '2',
    username: 'cinema_lover',
    filmCount: 45,
    likesCount: 12,
    visibility: 'private',
    createdAt: '2024-02-01T00:00:00Z',
    updatedAt: '2024-03-18T00:00:00Z',
  },
];

export const mockThreads: Thread[] = [
  {
    id: '1',
    title: 'What\'s the best film of 2024 so far?',
    userId: '2',
    username: 'cinema_lover',
    category: 'General',
    replyCount: 89,
    viewCount: 1200,
    status: 'open',
    createdAt: '2024-03-01T00:00:00Z',
    lastReplyAt: '2024-03-20T14:00:00Z',
  },
  {
    id: '2',
    title: 'Denis Villeneuve appreciation thread',
    userId: '3',
    username: 'film_critic_42',
    category: 'Directors',
    replyCount: 156,
    viewCount: 3400,
    status: 'pinned',
    createdAt: '2024-02-15T00:00:00Z',
    lastReplyAt: '2024-03-20T16:30:00Z',
  },
  {
    id: '3',
    title: 'Bug report: Can\'t save my list',
    userId: '2',
    username: 'cinema_lover',
    category: 'Support',
    replyCount: 5,
    viewCount: 45,
    status: 'closed',
    createdAt: '2024-03-18T00:00:00Z',
    lastReplyAt: '2024-03-19T10:00:00Z',
  },
];

const mockActivity: ActivityItem[] = [
  {
    id: '1',
    type: 'review',
    description: 'wrote a review for Dune: Part Two',
    user: 'cinema_lover',
    timestamp: '2 minutes ago',
  },
  {
    id: '2',
    type: 'user_joined',
    description: 'joined Lumières',
    user: 'new_cinephile',
    timestamp: '15 minutes ago',
  },
  {
    id: '3',
    type: 'film_added',
    description: 'added The Brutalist to the database',
    user: 'alex_morgan',
    timestamp: '1 hour ago',
  },
  {
    id: '4',
    type: 'list_created',
    description: 'created a new list: "Hidden Gems of 2024"',
    user: 'film_critic_42',
    timestamp: '3 hours ago',
  },
  {
    id: '5',
    type: 'report',
    description: 'flagged a review as spam',
    user: 'film_critic_42',
    timestamp: '5 hours ago',
  },
];

export const mockDashboardStats: DashboardStats = {
  totalFilms: 12543,
  totalUsers: 8721,
  totalReviews: 45892,
  totalLists: 3412,
  filmsTrend: 12.5,
  usersTrend: 8.3,
  reviewsTrend: 15.2,
  listsTrend: -2.1,
  recentActivity: mockActivity,
  chartData: [
    { label: 'Mon', value: 65 },
    { label: 'Tue', value: 78 },
    { label: 'Wed', value: 52 },
    { label: 'Thu', value: 91 },
    { label: 'Fri', value: 85 },
    { label: 'Sat', value: 110 },
    { label: 'Sun', value: 95 },
  ],
};
